Presentation/ViewModels/Controller/WorkerOrder/CreateWorkOrder.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Net.Http;

namespace Presentation.ViewModels
{
    [Serializable]
    public class CreateWorkOrder
    {
        [DisplayName("Location")]
        public int LocationId { get; set; }

        public List<SelectItem> Locations { get; set; }

        [Required]
        [DisplayName("Sub Location")]
        public int SubLocationId { get; set; }

        public List<SelectItem> SubLocation { get; set; }
        //public List<SelectItem> Items { get; set; }

        [DisplayName("Item")]
       
        public int? ItemId { get; set; }

        public int? VendorId { get; set; }
        public List<SelectItem> Vendors { get; set; }
        public List<SelectItem> Properties { get; set; }

        [Required(ErrorMessage = "Please Select Property")]
        [DisplayName("Property")]
        public long PropertyId { get; set; }

        public List<SelectItem> Issues { get; set; }

        [DisplayName("Issue")]
        [Required(ErrorMessage = "Please Select Issue")]
       
        public int IssueId { get; set; }

        [Required(ErrorMessage = "Please Give Some Detail")]
        public string Description { set; get; }
        [Required(ErrorMessage ="Please Select Assign to")]
        public string Category { get; set; }
        public List<SelectItem> Options { get; set; }
        [DisplayName("Option")]
        public int? OptionId { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DueDate { get; set; }
        
        public IList<IFormFile> File { get; set; }

        [Required]
        [Range(0, 3)]
        public int Priority { get; set; }
        [StringLength(100, ErrorMessage ="Limit to 100 characters")]
        public string CustomIssue { get; set; }
       
    }
}

Presentation/ViewModels/Controller/WorkerOrder/CreateWorkOrderRecurring.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Presentation.ViewModels
{
    [Serializable]
    public class CreateWorkOrderRecurring
    {
        [DisplayName("Location")]
        public int LocationId { get; set; }

        public List<SelectItem> Locations { get; set; }

        [Required]
        [DisplayName("Sub Location")]
        public int SubLocationId { get; set; }

        public List<SelectItem> SubLocation { get; set; }
        //public List<SelectItem> Items { get; set; }

        [DisplayName("Item")]
       
        public int? ItemId { get; set; }

        public int? VendorId { get; set; }
        public List<SelectItem> Vendors { get; set; }
        public List<SelectItem> Properties { get; set; }

        [Required(ErrorMessage = "Please Select Property")]
        [DisplayName("Property")]
        public long PropertyId { get; set; }

        public List<SelectItem> Issues { get; set; }

        [DisplayName("Issue")]
        [Required(ErrorMessage = "Please Select Issue")]
        public int IssueId { get; set; }

        [Required(ErrorMessage = "Please Give Some Detail")]
        public string Description { set; get; }
        [Required(ErrorMessage = "Please Select Assign to")]
        public string Category { get; set; }
        public List<SelectItem> Options { get; set; }
        [DisplayName("Option")]
        public int? OptionId { get; set; }

        [Required]
        [Range(0, 366)]
        public uint DueAfterDays { get; set; }

        public IList<IFormFile> File { get; set; }

        [Required]
        [Range(0, 3)]
        public int Priority { get; set; }
        [Required(ErrorMessage ="Please Enter Schedule Details")]
        public string CronExpression { get; set; }
        public DateTime? RecurringEndDate { get; set; }
        public int? EndAfterCount { get; set; }
        public DateTime? RecurringStartDate { get; set; }
        [StringLength(100, ErrorMessage = "Limit to 100 characters")]
        public string CustomIssue { get; set; }
    }
}

Presentation/ViewModels/Controller/WorkerOrder/WorkOrderDetail.cs
using Microsoft.AspNetCore.Http;
using Presentation.Utility;
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace Presentation.ViewModels
{
    public class WorkOrderDetail
    {
        public string Id { get; set; }

        [DisplayName("Property Name")]
        public string PropertyName { get; set; }

        [DisplayName("Sub Location")]
        public string SubLocation { get; set; }

        public string Location { get; set; }

        [DisplayName("Requested By")]
        public string Requestedby { get; set; }


        [DisplayName("Status")]
        public string StatusDescription { get; set; }

        public string Issue { get; set; }

        [DisplayName("Due Date")]
        public string DueDate { get; set; }
        public string Vendor { get; set; }

        public string Item { get; set; }

        [DisplayName("Created Time")]
        public DateTime CreatedTime { get; set; }

        public string Description { get; set; }
        public int Priority { get; set; }

        [DisplayName("Updated Time")]
        public DateTime UpdatedTime { get; set; }
      

        public List<KeyValuePair<string, string>> Attachment { get; set; }

        [DisplayName("Assigned To")]
        public string AssignedTo { get; set; }

        [DisplayName("Updated By")]
        public string UpdatedBy { get; set; }

        [SkipProperty]
        public List<SelectItem> Statuses { get; set; }

        [SkipProperty]
        public Pagination<List<Comment>> Comments { get; set; }
        public bool Recurring { get; set; }
        public DateTime? RecurringEndDate { get; set; }
        public int? EndAfterCount { get; set; }
        public string CronExpression { get; set; }
        public DateTime? RecurringStartDate { get; set; }
        public string ParentWOId { get; set; }
        public string FilesRemoved { get; set; }
        public int StatusId { get; set; }
        public IList<IFormFile> File { get; set; }
        public string StatusChangeComment { get; set; }

    }
}

Presentation/Controllers/WorkOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Presentation.ConstModal;
using Presentation.Utiliity.Interface;
using Presentation.Utility;
using Presentation.Utility.Interface;
using Presentation.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Wangkanai.Detection;

namespace Presentation.Controllers
{
    [ReferrerAttribute]
    public class WorkOrderController : Controller
    {
        private readonly IHttpClientHelper _httpClientHelper;
        private readonly IOptions<RouteConstModel> _apiRoute;
        private readonly string _token;
        private readonly IExport<WorkOrderDetail> _export;
        private readonly IExport<AllWOExport> _allwoexport;
        private readonly IExport<AllWOExportRecurring> _allrecurringwoexport;
        private readonly IDetection _detection;

        public WorkOrderController(IHttpClientHelper httpClientHelper, IOptions<RouteConstModel> apiRoute, IHttpContextAccessor httpContextAccessor, IDistributedCache _session, IExport<WorkOrderDetail> export, IExport<AllWOExport> allwoexport, IDetection detection, IExport<AllWOExportRecurring> allrecurringwoexport)
        {
            _httpClientHelper = httpClientHelper;
            _apiRoute = apiRoute;
            if (httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                var id = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Sid).Value;
                var returnval = ObjectByteConverter.Deserialize<SessionStore>(_session.Get(id));
                if (returnval != null)
                    _token = returnval.Token;

            }
            _export = export;
            _allwoexport = allwoexport;
            _detection = detection;
            _allrecurringwoexport = allrecurringwoexport;
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Index(WOFilterModel wOFilterModel)
        {
            try
            {
                wOFilterModel.IsActive = true;
                _apiRoute.Value.Routes.TryGetValue("getallworkorder", out string path);
                StringBuilder query = new StringBuilder();
                var response = await _httpClientHelper.PostDataAsync(_apiRoute.Value.ApplicationBaseUrl + path, wOFilterModel, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                {
                    var WorkOrderAssigned = JsonConvert.DeserializeObject<Pagination<List<WorkOrderAssigned>>>(await response.Content.ReadAsStringAsync());
                    ViewBag.Response = WorkOrderAssigned;
                }
            }
            catch (Exception)
            {
            }
            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/WorkOrder/Mobile/Index.cshtml", wOFilterModel);
            return View(wOFilterModel);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> CreateWorkOrderView()
        {

            CreateWorkOrder createWorkOrder = new CreateWorkOrder();
            
            _apiRoute.Value.Routes.TryGetValue("getworkordermodel", out string path);
            var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path, this, _token).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
                createWorkOrder = JsonConvert.DeserializeObject<CreateWorkOrder>(await response.Content.ReadAsStringAsync());


            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/WorkOrder/Mobile/CreateWorkOrder.cshtml", createWorkOrder);
           else
            return View("CreateWorkOrder", createWorkOrder);
           
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> CreateWorkOrderRecurringView()
        {

            CreateWorkOrderRecurring createWorkOrder = new CreateWorkOrderRecurring();

            _apiRoute.Value.Routes.TryGetValue("getworkordermodel", out string path);
            var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path, this, _token).ConfigureAwait(false);
            if (response.IsSuccessStatusCode)
                createWorkOrder = JsonConvert.DeserializeObject<CreateWorkOrderRecurring>(await response.Content.ReadAsStringAsync());


            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/WorkOrder/Mobile/CreateWorkOrderRecurring.cshtml", createWorkOrder);
           
            else
                return View("CreateWorkOrderRecurring", createWorkOrder);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetSubLocation(long id)
        {
            List<SelectItem> result = null;
            try
            {
                _apiRoute.Value.Routes.TryGetValue("getsublocation", out string path);
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?id=" + id, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                    result = JsonConvert.DeserializeObject<List<SelectItem>>(await response.Content.ReadAsStringAsync());
            }
            catch (Exception)
            {
            }
            return Ok(result);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetLocation(long id)
        {
            List<SelectItem> result = null;
            try
            {
                _apiRoute.Value.Routes.TryGetValue("getlocation", out string path);
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?id=" + id, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                    result = JsonConvert.DeserializeObject<List<SelectItem>>(await response.Content.ReadAsStringAsync());
            }
            catch (Exception)
            {
            }
            return Ok(result);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> GetDataByCategory(string category)
        {
            Dictionary<string, List<SelectItem>> result = null;
            try
            {
                _apiRoute.Value.Routes.TryGetValue("getdatabycategory", out string path);
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?category=" + category, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                    result = JsonConvert.DeserializeObject<Dictionary<string, List<SelectItem>>>(await response.Content.ReadAsStringAsync());
            }
            catch (Exception)
            {
            }
            return Ok(result);
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult<WorkOrderDetail>> GetWODetail(string id,int type=1)
        {
            WorkOrderDetail workOrderDetail = null;

            try
            {
                string path;
                if (type == 2)
                {
                    _apiRoute.Value.Routes.TryGetValue("getrecwodetail", out path);
                }
                else {
                    _apiRoute.Value.Routes.TryGetValue("wodetail", out path);
                }
            
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?id=" + id, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                {
                    workOrderDetail = JsonConvert.DeserializeObject<WorkOrderDetail>(await response.Content.ReadAsStringAsync());
                }
            }
            catch (Exception)
            {
            }
            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/WorkOrder/Mobile/WorkOrderDetail.cshtml", workOrderDetail);
            return View("WorkOrderDetail", workOrderDetail);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> EditWOView(string id)
        {
            EditWorkOrder editWorkOrder = null;
            try
            {
                _apiRoute.Value.Routes.TryGetValue("editWOModel", out string path);
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?id=" + id, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                {
                    editWorkOrder = JsonConvert.DeserializeObject<EditWorkOrder>(await response.Content.ReadAsStringAsync());
                }
            }
            catch (Exception ex)
            {
            }
            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/WorkOrder/Mobile/EditWOView.cshtml", editWorkOrder);
            return View(editWorkOrder);
        }
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> EditRecurringWOView(string id)
        {
            EditRecurringWorkOrder editWorkOrder = null;
            try
            {
                _apiRoute.Value.Routes.TryGetValue("editRecurringwomodel", out string path);
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?id=" + id, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                {
                    editWorkOrder = JsonConvert.DeserializeObject<EditRecurringWorkOrder>(await response.Content.ReadAsStringAsync());
                }
            }

Presentation/Views/WorkOrder/Mobile/CreateWorkOrder.cshtml
@model CreateWorkOrder
@{
    ViewData["Title"] = "Create WorkOrder";
    Layout = "~/Views/Shared/_Layout.cshtml";
    //margin
    var bottom = "0";
    var height="92%";
    var context=HttpContextAccessor.HttpContext.Request.Headers["User-Agent"].ToString();
    if (context.Contains("iPhone"))
    {
        height = "90%";
        bottom = "2%";
    }

}
<header>
    <nav class="navbar bg-success mb-3 fixed-top">
        <div class="d-inline-flex w-100">
            <a style="color:white" href="javascript:history.back()" class="nav-link"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></a>
            <div class="container-block justify-content-center">
                <span class="nav-link justify-content-end" style="color:white;font-size:1.5em;">Create Work Order</span>
            </div>
        </div>
    </nav>
</header>

<form class="mform" style="height: @height;bottom:@bottom" id="wocreate" asp-action="CreateWO" asp-controller="WorkOrder">
    <input type="text" id="Referer" name="Referer" hidden value="@ViewBag.Referer" />
    @if (Model == null)
    {
        <p>No Record Found</p>
    }
    else
    {
        <table class="table table-striped">
            <tbody>
                <tr>
                    <th>
                        Location
                    </th>
                </tr>
                <tr>
                    <td>

                        @if (Model.Properties != null)
                        {
                            <div class="row padding">

                                <select class="form-control form-control" asp-for="PropertyId" asp-items="@(new SelectList(Model.Properties, "Id", "PropertyName"))">
                                    <option value="">Property</option>
                                </select>
                                <span asp-validation-for="PropertyId" class="text-danger"></span>
                            </div>
                        }
                        <div class="row top-buffer padding">

                            @if (Model.Locations != null)
                            {
                                <select id="LocationId" name="LocationId" class="form-control" asp-items="@(new SelectList(Model.Locations, "Id", "PropertyName"))">
                                    <option value="">Select Location</option>
                                </select>
                            }
                            else
                            {
                                <select id="LocationId" name="LocationId" class="form-control ">
                                    <option value="">Select Location</option>
                                </select>
                            }
                        </div>

                        <div class="row top-buffer padding">

                            <select class="form-control " asp-for="SubLocationId">
                                <option value="">Select Sublocation</option>
                            </select>
                            <span asp-validation-for="SubLocationId" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
                        What
                    </th>
                </tr>
                <tr>
                    <td>

                        <div class="row padding">

                            <select asp-for="ItemId" class="form-control">
                                <option value="">Select Item</option>
                            </select>

                            <span asp-validation-for="ItemId" class="text-danger"></span>
                        </div>


                        <div class="row top-buffer padding">

                            <select class="form-control" asp-for="IssueId">
                                <option value="">Select Issue</option>
                                <option selected value="-1">Other</option>
                            </select>
                            <span asp-validation-for="IssueId" class="text-danger"></span>
                        </div>
                        <div class="row top-buffer padding CustomIssueDiv" style="@if (String.IsNullOrEmpty(Model.CustomIssue)) { <text>display:none</text>}">
                            <textarea class="form-control" placeholder="Write your own issue. Limit to 100 characters." asp-for="CustomIssue"></textarea>

                        </div>

                    </td>
                </tr>

                <tr>
                    <th>
                        Details
                    </th>
                </tr>
                <tr>
                    <td>
                        <div class="row padding">

                            <textarea class="form-control " asp-for="Description" placeholder="Additional Details"></textarea>
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
                        Priority
                    </th>
                </tr>
                <tr>
                    <td>
                        <div class="row padding">
                            <select asp-for="Priority" class="form-control">
                                <option value="0">Critical</option>
                                <option value="1">High</option>
                                <option value="2" selected>Medium</option>
                                <option value="3">Low</option>
                            </select>
                            <span asp-validation-for="Priority" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                <tr>
                    <th>
                        Due Date
                    </th>
                </tr>
                <tr>
                    <td>
                        <div class="row padding">
                            <input class="form-control" asp-for="DueDate">
                            <span asp-validation-for="DueDate" class="text-danger"></span>
                        </div>
                    </td>
                </tr>
                @if (Model.Vendors != null && Model.Vendors.Any())
                {
                    <tr>
                        <th>
                            Vendor (Optional)
                        </th>
                    </tr>
                    <tr>
                        <td>
                            <div class="row top-buffer padding">
                                <select class="form-control form-control" asp-for="VendorId" asp-items="@(new SelectList(Model.Vendors, "Id", "PropertyName"));">
                                    <option value="">Select Vendor</option>
                                </select>
                                <span asp-validation-for="VendorId" class="text-danger"></span>
                            </div>
                        </td>
                    </tr>
                }
                <tr>
                    <th>Assign To</th>
                </tr>
                <tr>
                    <td>
                        <div class="row padding">
                            <select class="form-control " asp-for="Category">
                                <option value="">Choose One</option>
                                <option selected value="department">Department</option>
                                <option value="user">User</option>
                                <option value="anyone">Anyone</option>
                            </select>
                            <span asp-validation-for="Category" class="text-danger"></span>
                        </div>
                        <div class="row padding top-buffer">

                            <select class="form-control" asp-for="OptionId">
                                <option value="">Select Option</option>
                            </select>

                        </div>
                    </td>
                </tr>
                <tr>
                    <th>Add files</th>
                </tr>
                <tr>
                    <td>
                        <div class="row top-buffer">
                            <div class="col-md-3">
                                <label for="File">Attachment</label>
                            </div>
                            <div class="col">
                                <div class="cont" style="width:100%">
                                    <label style="width:100%" class="browsebutton">Add Photo</label>
                                    <input style="width:100%" asp-for="File" accept="image/*,.pdf,.xls,.xlx,.doc,.docx" class="form-control-sm custom-input File" multiple>
                                </div>
                                <div id="file_selected">
                                </div>
                                <span class="text-danger">supported formats: .jpg, .jpeg, .png, .pdf, .xls, .xlx, .doc, .docx </span>
                                <p class="text-danger">Photo uploads are not added until work order is saved.</p>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <hr />
        <div class="bottom-section" style="padding-bottom:@bottom">
            <div class="bottom-stick" style="padding:5px;">
                <button type="submit" data-toggle="modal" style="margin-left: 24%;" data-target=".bd-example-modal-lg" class="btn w-50 btn-success submit">Create</button>
            </div>
        </div>
    }
</form>

Presentation/Views/WorkOrder/Mobile/GetChildWO.cshtml
@model Pagination<List<ChildWo>>

@if (Model != null && Model.Payload != null && Model.Payload.Any())
{
    <table class="table table-striped border-0 wordorderdetail table_container table-responsive-lg">

        <tbody>

            @foreach (var item in Model.Payload)
            {
                <tr>
                    <td>
                        <span><strong class="green">@item.Id</strong></span>
                    </td>

                    <td><span class="value" style="min-width:100px;text-align:left">@item.Description</span></td>
                    <td>Assigned to&nbsp;<span class="text-success"><strong>@item.AssignedTo</strong></span></td>
                    <td>
                        <span class="text-dark">
                            @if (item.Property != null)
                            {@item.Property.PropertyName}
                        </span>
                    </td>
                    <td>@item.DueDate</td>
                    <td style="min-width:180px;">
                        <div class="form-inline">
                            @{
                                Dictionary<string, string> keyValuePairs = new Dictionary<string, string>();
                                keyValuePairs.Add("id", item.Id + "");

                                <auth-link bclass="btn btn-sm btn-primary mr-1" feature=@MenuEnum.Edit_WO routedata=@keyValuePairs action="EditWOView" controller="WorkOrder" content='<i class="fa fa-pencil-alt"></i>&nbsp;Edit'></auth-link>

                                <auth-link bclass="btn btn-sm btn-info" feature=@MenuEnum.GetWO_Detail routedata=@keyValuePairs action="GetWODetail" controller="WorkOrder" content='<i class="fa fa-info"></i>&nbsp;Detail'></auth-link>
                            }
                        </div>
                    </td>
                </tr>
            }
        </tbody>

    </table>

    <hr />
    <nav>
        <ul class="pagination m-1">
            @{ int prev = Model.CurrentPage - 1;}
            <li class="page-item @if (Model.CurrentPage == 0)
                {<text>disabled</text> }">
                <a class="page-link" asp-action="GetRecurringWO" asp-controller="WorkOrder" asp-route-pageNumber='@prev'>Prev</a>
            </li>

            @for (int i = 0; i < Model.PageCount; i++)
            {

                if (Model.CurrentPage == i)
                {
                    <li class="page-item active" >
                        <a class="page-link " >@(i + 1) <span class="sr-only">(current)</span></a>
                    </li>

                }
                else
                {
                    var x = i + 1;
                    <li class="page-item">
                        <a class="page-link" asp-action="GetRecurringWO" asp-controller="WorkOrder" asp-route-pageNumber='@x'>@x</a>

                    </li>
                }
            }
            @{ var PageNumber = Model.CurrentPage + 1;}
            <li class="page-item @if (Model.CurrentPage + 1 == Model.PageCount)
                    {<text>disabled</text> }">
                <a class="page-link" asp-action="GetRecurringWO" asp-controller="WorkOrder" asp-route-pageNumber='@PageNumber'>Next</a>
            </li>
        </ul>
    </nav>
}
else
{
    <span>No Record found</span>
}



<script>
    var workorderId = '@Model.Payload[0].ParentId';
    function GetPage(pagenumber) {
            $.get('@Url.Action("GetChildWO","WorkOrder")' + '?rwoId=' + workorderId + '&search=&pageNumber='+pagenumber,
                function (data) {
                    if (data != null || data != undefined) {
                        $('#ChildWOSection').html(data);
                    }
                });
    }

</script>