Presentation/ViewModels/Controller/User/PropertyConfig.cs
using System.Collections.Generic;
using System.ComponentModel;

namespace Presentation.ViewModels
{
    public class PropertyConfig
    {
        public long PropertyId { get; set; }
        public  string Name { get; set; }
        public List<SelectItem> Locations { set; get; }
        public int? LocationId { get; set; }
        public string NewLocation { get; set; }

        [DisplayName("Sub Location")]
        public string SubLocation { set; get; }
        
    }
}

Presentation/Controllers/PropertyController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Presentation.ConstModal;
using Presentation.Utility;
using Presentation.Utility.Interface;
using Presentation.ViewModels;
using Presentation.ViewModels.Controller.User;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using Wangkanai.Detection;

namespace Presentation.Controllers
{
    
    public class PropertyController : Controller
    {
        private readonly IHttpClientHelper _httpClientHelper;
        private readonly IOptions<RouteConstModel> _apiRoute;
        private readonly string _token;
        private readonly IDetection _detection;

        public PropertyController(IHttpClientHelper httpClientHelper, IOptions<RouteConstModel> apiRoute, IHttpContextAccessor httpContextAccessor, IDetection detection,IDistributedCache _session)
        {
            _httpClientHelper = httpClientHelper;
            _apiRoute = apiRoute;
            if (httpContextAccessor.HttpContext.User.Identity.IsAuthenticated)
            {
                var id = httpContextAccessor.HttpContext.User.FindFirst(ClaimTypes.Sid).Value;
                var returnval = ObjectByteConverter.Deserialize<SessionStore>(_session.Get(id));
                if (returnval != null)
                    _token = returnval.Token;

            }
            _detection = detection;
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> AddPropertyView()
        {
            PropertyOperation addProperty = new PropertyOperation();
            try
            {
                HttpContext.Session.TryGetValue("token", out var token);
                _apiRoute.Value.Routes.TryGetValue("getPropertyTypes", out string path);
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                    addProperty = JsonConvert.DeserializeObject<PropertyOperation>(await response.Content.ReadAsStringAsync());
            }
            catch (Exception)
            {
                TempData["Error"] = StringConstants.Error;
            }
            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/Property/Mobile/AddPropertyView.cshtml", addProperty);
            return View("AddPropertyView", addProperty);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddProperty(PropertyOperation model)
        {
            if (ModelState.IsValid)
            {
                _apiRoute.Value.Routes.TryGetValue("addproperty", out string path);
                try
                {
                    var response = await _httpClientHelper.PostDataAsync(_apiRoute.Value.ApplicationBaseUrl + path, model, this, _token).ConfigureAwait(false);
                    if (response.IsSuccessStatusCode && await response.Content.ReadAsStringAsync() == "true")
                        return Ok(StringConstants.CreatedSuccess);
                    else if (response.StatusCode == HttpStatusCode.BadRequest)
                        return StatusCode((int)response.StatusCode, await response.Content.ReadAsStringAsync());
                    else if (response.StatusCode == HttpStatusCode.Unauthorized)
                        return Content("<script language='javascript' type='text/javascript'>location.reload(true);</script>");
                    else
                        return StatusCode((int)HttpStatusCode.InternalServerError, StringConstants.Error);
                }
                catch (Exception)
                {
                    return StatusCode((int)HttpStatusCode.InternalServerError, StringConstants.Error);
                }
            }
            else
            {
               string msg = String.Join(", ", ModelState.Where(x => x.Value.Errors.Count > 0).SelectMany(x => x.Value.Errors.Select(y => y.ErrorMessage)).ToList());
                return StatusCode(500, msg);
            }
        }

        [HttpGet]
        
        [Authorize]
        public async Task<ActionResult> ListProperties()
        {
            _apiRoute.Value.Routes.TryGetValue("listproperties", out string path);
            List<Properties> properties = new List<Properties>();
            try
            {
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                    properties = JsonConvert.DeserializeObject<List<Properties>>(await response.Content.ReadAsStringAsync());
            }
            catch (Exception)
            {
                TempData["Error"] = StringConstants.Error;
            }
            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/Property/Mobile/ListProperties.cshtml", properties);
            return View(properties);
        }

        [HttpGet]
        [Authorize]
        public async Task<ActionResult> ActDeactProperty(int id, bool operation)
        {
            if (id == 0)
            {
                //TempData["Error"] = "Unable to Activate/Deactivate property";
                return RedirectToAction("ListProperties");
            }
            try
            {
                _apiRoute.Value.Routes.TryGetValue("actdeactproperty", out string path);
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?id=" + id + "&operation=" + operation, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                {
                    
                }
            }
            catch (Exception)
            {
                TempData["Error"] = StringConstants.Error;
            }
            return RedirectToAction("ListProperties");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> UpdateProperty(PropertyOperation prop)
        {
            _apiRoute.Value.Routes.TryGetValue("updateproperty", out string path);
            if (ModelState.IsValid)
            {
                try
                {
                    var response = await _httpClientHelper.PostDataAsync(_apiRoute.Value.ApplicationBaseUrl + path, prop, this, _token).ConfigureAwait(false);
                    if (response.IsSuccessStatusCode)
                        TempData["Success"] = StringConstants.SuccessUpdate;
                }
                catch (Exception)
                {
                    TempData["Error"] = StringConstants.Error;
                }
            }
            else
            {
                TempData["Error"] = String.Join(", ", ModelState.Where(x => x.Value.Errors.Count > 0).SelectMany(x => x.Value.Errors.Select(y => y.ErrorMessage)).ToList());
            }

            return RedirectToAction("ListProperties", new { id = prop.Id });
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> PropertyEditView(long id)
        {
            _apiRoute.Value.Routes.TryGetValue("getproperty", out string path);
            PropertyOperation prop = new PropertyOperation();
            try
            {
                var response = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?id=" + id, this, _token).ConfigureAwait(false);
                if (response.IsSuccessStatusCode)
                    prop = JsonConvert.DeserializeObject<PropertyOperation>(await response.Content.ReadAsStringAsync());
            }
            catch (Exception)
            {
                TempData["Error"] = StringConstants.Error;
            }
            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/Property/Mobile/PropertyEditView.cshtml", prop);
            return View(prop);
        }

        [HttpGet]
        [Authorize]
        public async Task<JsonResult> CheckProperty(string propertyName)
        {
            Boolean result;
            try
            {
                _apiRoute.Value.Routes.TryGetValue("checkproperty", out var path);
                var res = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?propertyName=" + propertyName, this, _token);
                if (res.IsSuccessStatusCode)
                {
                    result = Convert.ToBoolean(await res.Content.ReadAsStringAsync());
                    if (result)
                        return Json("Property Name Already Present");
                }
            }
            catch (Exception) { }
            return Json(true);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> PropertyConfig(long Id)
        {
            PropertyConfig result = null;
            try
            {
                _apiRoute.Value.Routes.TryGetValue("propertyconfig", out var path);
                var res = await _httpClientHelper.GetDataAsync(_apiRoute.Value.ApplicationBaseUrl + path + "?Id=" + Id, this, _token);
                if (res.IsSuccessStatusCode)
                {
                    result = JsonConvert.DeserializeObject<PropertyConfig>(await res.Content.ReadAsStringAsync());
                }
            }
            catch (Exception) { }
            if (_detection.Device.Type == DeviceType.Mobile)
                return View("~/Views/Property/Mobile/PropertyConfig.cshtml", result);
            return View("PropertyConfig", result);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> PropertyConfig(PropertyConfig propertyConfig)

Presentation/Views/Property/Mobile/AddPropertyView.cshtml
@model Presentation.ViewModels.PropertyOperation
@{
    ViewData["Title"] = "Add Property";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Scripts
{
    <partial name="_ValidationScriptsPartial" />
}
<header>
    <nav class="navbar bg-success mb-3 fixed-top">
        <div class="d-inline-flex w-100">
            <a style="color:white" asp-action="ListProperties" class="nav-link"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></a>
            <div class="container-block justify-content-center">
                <span class="nav-link justify-content-end" style="color:white;font-size:1.5em;">Add Property</span>
            </div>
        </div>
    </nav>
</header>
<div class="mform" style="padding-left:5px; padding-right:5px;">
    <hr>
    @if (Model != null)
    {
    <form asp-action="AddProperty" asp-controller="Property" id="addprop">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <table class="table table_container">
            <tbody>
                <tr>
                    <td>
                        <div class="col">
                            <div class="row ">
                                <div class="col-md-3">
                                    <label for="PropertyTypeId">Property Type</label>
                                </div>
                                <div class="col">
                                    @if (Model.PropertyTypes != null)
                                {
                                    <select class="form-control form-control-sm custom-input" asp-for="PropertyTypeId" asp-items="@(new SelectList(Model.PropertyTypes, "Id", "PropertyName"))">
                                        <option value="">Select Property</option>
                                    </select>
                                }
                                    <span asp-validation-for="PropertyTypeId" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row top-buffer ">
                                <div class="col-md-3">
                                    <label for="PropertyName">Property Name </label>
                                </div>
                                <div class="col">
                                    <input asp-for="PropertyName" class="form-control-sm custom-input">
                                    <span asp-validation-for="PropertyName" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col">

                            <div class="row">
                                <div class="col-md-3">
                                    <label asp-for="StreetAddress1"></label>
                                </div>
                                <div class="col">
                                    <input asp-for="StreetAddress1" class="form-control-sm custom-input">
                                    <span asp-validation-for="StreetAddress1" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row top-buffer">
                                <div class="col-md-3">
                                    <label asp-for="StreetAddress2"></label>
                                </div>
                                <div class="col">
                                    <input asp-for="StreetAddress2" class="form-control-sm custom-input">
                                    <span asp-validation-for="StreetAddress2" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col">

                            <div class="row top-buffer">
                                <div class="col-md-3">
                                    <label asp-for="City"> </label>
                                </div>
                                <div class="col">
                                    <input asp-for="City" class="form-control-sm custom-input">
                                    <span asp-validation-for="City" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row top-buffer">
                                <div class="col-md-3">
                                    <label asp-for="ZipCode"></label>
                                </div>
                                <div class="col">
                                    <input asp-for="ZipCode" class="form-control-sm custom-input">
                                    <span asp-validation-for="ZipCode" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row top-buffer">
                                <div class="col-md-3">
                                    <label asp-for="State"> </label>
                                </div>
                                <div class="col">
                                    <input asp-for="State" class="form-control-sm custom-input">
                                    <span asp-validation-for="State" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row top-buffer">
                                <div class="col-md-3">
                                    <label asp-for="Country"> </label>
                                </div>
                                <div class="col">
                                    <input asp-for="Country" class="form-control-sm custom-input">
                                    <span asp-validation-for="Country" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <hr />
        <div class="bottom-stick" style="padding:5px;">
            <button type="submit" data-toggle="modal" data-target=".bd-example-modal-lg" class="btn w-50  btn-success submit">Add Property</button>
            <input type="reset" class="btn btn-sm btn-danger w-50" value="Reset" name="reset" style="margin-left:5px;">
        </div>
    </form>
    }
</div>

Presentation/Views/Property/Mobile/ListProperties.cshtml
@model IEnumerable<Properties>
@{
    ViewData["Title"] = "ListProperties";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<header>
    <nav class="navbar navbar-dark bg-success border-bottom box-shadow mb-3 fixed-top">
        <div class="container-fluid">
            <a class="navbar-brand justify-content-center" asp-controller="WorkOrder" asp-action="Index">Properties</a>
            <ul class="navbar-nav justify-content-end" style="flex-direction:row;">
                <li class="nav-item" style="margin-right:5px;">
                    <a class="nav-link text-white" asp-controller="Login" asp-action="Mobile"><i class="fa fa-bars fa-1x" aria-hidden="true"></i></a>
                </li>
            </ul>
        </div>
    </nav>
</header>
<div class="mform" style="padding-left:5px;padding-right:5px;">
    <hr />
    @if (Model != null)
{
    <p>
        <auth-link bclass="btn btn-sm btn-success addmodal" action="AddPropertyView" controller="Property" feature=@MenuEnum.Add_Property content='<i class="fa fa-plus fa-1x"></i>&nbsp;Create New'></auth-link>
    </p>
    <div class="new_address_css">
        @if (Model == null || !Model.Any())
        {
        <div>No properties Found</div>
        }
        else
        {
            foreach (var item in Model)
            {
        <div class="card propetry">
            <div class="card-header propery_head">
                <ul class="opertion_menu">
                    @{
                                Dictionary<string, string> keyValuePairs = new Dictionary<string, string>();
                                keyValuePairs.Add("id", item.Id + "");
                    }
                    <li class="opertion_menu_item"><auth-link bclass="opertion_menu_item" feature=@MenuEnum.Edit_Property routedata=@keyValuePairs action="PropertyEditView" controller="Property" content='<i class="fa fa-pencil-alt fa-1x" aria-hidden="true"></i>'></auth-link></li>
                    <li class="opertion_menu_item">
                        <a asp-action="PropertyConfig" asp-controller="Property" asp-route-id="@item.Id"><i class="fa fa-cogs fa-1x" aria-hidden="true"></i></a>
                    </li>
                    @{keyValuePairs.Add("operation", !item.IsActive + "");
                    }

                    @if (item.IsActive)
                            {

                    <li class="opertion_menu_item"><auth-link bclass="opertion_menu_item" feature=@MenuEnum.Act_Deact_Property routedata=@keyValuePairs action="ActDeactProperty" controller="Property" content="<i class='fas fa-toggle-on fa-1x'></i>"></auth-link></li>
                            }
                            else
                            {
                    <li class="opertion_menu_item"><auth-link bclass="opertion_menu_item" feature=@MenuEnum.Act_Deact_Property routedata=@keyValuePairs action="ActDeactProperty" controller="Property" content="<i style='color:red' class='fas fa-toggle-off fa-1x'></i>"></auth-link></li>

                            }
                </ul>
            </div>
            <div class="card-body">
                <h5 class="card-title">@item.PropertyName</h5>
                <p class="card-text">
                    <address>
                        <strong>@item.PropertyType</strong><br>
                        @item.StreetAddress1<br>
                        @item.StreetAddress2<br>
                        @item.City @item.State<br>
                        @item.ZipCode @item.Country<br>
                    </address>
                </p>
            </div>
        </div>
            }
        }
    </div>
}
</div>
@if (TempData.ContainsKey("Error") || TempData.ContainsKey("Success"))
{
    var key = TempData.ContainsKey("Error") ? "Error" : TempData.ContainsKey("Success") ? "Success" : "Info";

<script>
        alertify.alert('@key', '<p>@TempData[key]</p>', function () { });
</script>
}

Presentation/Views/Property/Mobile/PropertyConfig.cshtml
@model PropertyConfig
@{
    ViewData["Title"] = "Property Config";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<header>
    <nav class="navbar bg-success mb-3 fixed-top">
        <div class="d-inline-flex w-100">
            <a style="color:white" asp-action="ListProperties" class="nav-link"><i class="fa fa-chevron-left fa-2x" aria-hidden="true"></i></a>
            <div class="container-block justify-content-center">
                <span class="nav-link justify-content-end" style="color:white;font-size:1.5em;">Property Config</span>
            </div>
        </div>
    </nav>
</header>
<div class="mform" style="padding-left:5px; padding-right:5px;">
    <hr />
    <div style="text-align:center;font-weight:bold">@Model.Name</div>
    <form asp-action="PropertyConfig" class="addconfig">
        <table class="table table_container">
            <tbody>
                <tr>
                    <td>

                        <div class="col">
                            <div class="row">
                                <div class="col-md-3">
                                </div><div class="col">
                                    <div class="form-check">
                                        <input class="form-check-input" onclick="ShowNewLocation();" type="checkbox" value="true" id="flexCheckDefault">
                                        <label class="form-check-label" for="flexCheckDefault">
                                            New Location
                                        </label>
                                    </div>

                                </div>
                            </div>
                            @if (Model.Locations != null && Model.Locations.Any())
                            {
                                <div class="row top-buffer" id="available-location">
                                    <div class="col-md-3">
                                        <label for="Locations">Location Available</label>
                                    </div>
                                    <div class="col">
                                        <select class="form-control form-control-sm custom-input" asp-for="LocationId" asp-items="@(new SelectList(Model.Locations, "Id", "PropertyName"))">
                                            <option value=""> Select Location</option>
                                        </select>
                                        <span asp-validation-for="LocationId" class="text-danger"></span>
                                        <div><input type="button" class="btm btn-sm btn-danger mt-1" value="Delete" onclick="deleteProp()"></div>

                                    </div>

                                </div>
                            }

                            <div class="row top-buffer" id="new-location" style="display:none;">
                                <div class="col-md-3">
                                    <label for="NewLocation">New Location</label>
                                </div>
                                <div class="col">
                                    <input asp-for="NewLocation" class="form-control form-control-sm custom-input">
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col">
                            <div class="row ">
                                <div class="col-md-3">
                                    <label asp-for="SubLocation"></label>
                                </div>
                                <div class="col">
                                    <textarea asp-for="SubLocation" rows="8" cols="8" class="form-control form-control-sm custom-input"></textarea>
                                    <span class="text-danger">Enter , speparated Sub Location</span><br />
                                    <span class="text-info">Sub Location will come prepopulated if available to corresponding location</span>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col">
                            <div class="row ">
                                <div class="col-md-3">
                                    <label>Asset Manager</label>
                                </div>
                                <div class="col">
                                    <a href="/property/AssetManager" >Click here</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>

               
            </tbody>
        </table>
        @*<table class="table table_container">
            <tbody>
                <tr>
                    <td>
                        <div class="col">
                            @if (Model.Locations != null && Model.Locations.Any())
                            {
                                <div class="row ">
                                    <div class="col-md-3">
                                        <label for="Locations">Location Available</label>
                                    </div>
                                    <div class="col">
                                        <select class="form-control form-control-sm custom-input" asp-for="LocationId" asp-items="@(new SelectList(Model.Locations, "Id", "PropertyName"))">
                                            <option value="">Select Location</option>
                                        </select>
                                        <span asp-validation-for="LocationId" class="text-danger"></span>
                                    </div>
                                </div>
                            }
                            <div class="row top-buffer">
                                <div class="col-md-3">
                                    <label for="NewLocation">New Location</label>
                                </div>
                                <div class="col">
                                    <input asp-for="NewLocation" class="form-control form-control-sm custom-input">
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>
                <tr>
                    <td>
                        <div class="col">
                            <div class="row ">
                                <div class="col-md-5">
                                    <label asp-for="SubLocation"></label>
                                </div>
                                <div class="col">
                                    <textarea asp-for="SubLocation" class="form-control form-control-sm custom-input"></textarea>
                                    <span class="text-danger">Enter , speparated Sub Location</span><br />
                                    <span class="text-info">Sub Location will come prepopulated if available to corresponding location</span>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>

            </tbody>
        </table>*@
        <div class="bottom-stick" style="background-color:white">
            <input asp-for="PropertyId" hidden>
            <button type="submit" class="btn w-100  btn-success submit">Save Changes</button>
        </div>
    </form>
</div>

<script>

    $('#LocationId').change(function () {
         $.get('@Url.Action("GetPropertyData","Property")' + "?id=" + $(this).val(),
                function (data) {
                    if (data != null || data != undefined) {
                        
                        
                        $("#SubLocation").val(data)
                        
                    }
                });
    })
    $("#SubLocation ").change(function (e) {
        if ($(this).val().indexOf(',') == $(this).val().length - 1) {
            alert("Please remove ',' from the end of input");
            $("input[type='submit']").prop("disabled", true);
        }
        else {
            $("input[type='submit']").prop("disabled", false);
        }
    })
</script>
@if (TempData.ContainsKey("Error") || TempData.ContainsKey("Success"))
{
    var key = TempData.ContainsKey("Error") ? "Error" : TempData.ContainsKey("Success") ? "Success" : "Info";

<script>
       @if (key == "Success")
    {
     <text>alertify.success(@TempData["Sccess"]);</text>
    }
    @if (key == "Error")
    {
     <text>alertify.error(@TempData["Error"]);</text>
    }
</script>
}